creating your first array

In [3]:
import numpy as np
temperatures=np.array([34,32,30,29,47])
print(temperatures)
print(("type:",type(temperatures)))


[34 32 30 29 47]
('type:', <class 'numpy.ndarray'>)


basic math on entire arrays at once

In [7]:
import numpy as np
prices=np.array([100,200,300,400])
prices_with_tax=prices*1.20
print(prices_with_tax)

[120. 240. 360. 480.]


2d arrays

In [9]:
import  numpy as np
marks=np.array([
    [88,89,70],
    [80,99,96],
    [87,78,87]
])
print(marks)
print("shape(rows,columns):",marks.shape)

[[88 89 70]
 [80 99 96]
 [87 78 87]]
shape(rows,columns): (3, 3)


useful built in function

In [1]:
import numpy as np
scores=np.array([45,67,77,90,50])
print("maximum score:",scores.max())
print("minimum score:",scores.min())
print("average score:",scores.mean())
print("total score:",scores.sum())
print("sorted scores:",np.sort(scores))

maximum score: 90
minimum score: 45
average score: 65.8
total score: 329
sorted scores: [45 50 67 77 90]


In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [10]:
import numpy as np
scores=np.array([45,67,77,90,50])
print("maximum score:",scores.max())
print("minimum score:",scores.min())
print("average score:",scores.mean())
print("total score:",scores.sum())
print("sorted scores:",np.sort(scores))

maximum score: 90
minimum score: 45
average score: 65.8
total score: 329
sorted scores: [45 50 67 77 90]


1d array

In [9]:
a = np.array([1,2,3])

print(a.ndim)

1


2d array

In [10]:
a = np.array([[1,2],[3,4]])

print(a.ndim)

2


check shape

In [23]:
import numpy as np
arr=np.array([
    [10,20,30],                             
    [40,50,60]
])
print(arr.shape)

(2, 3)


comparison

In [24]:
a>50

array([[False, False],
       [False, False]])

checksize

In [25]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.size)

4


data type

In [26]:
import numpy as np
a=np.zeros((2,3))
a=np.zeros((2,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]


identify matrix

In [27]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


arithmetic operation

In [ ]:
import numpy as np
marks=np.array([80,90,60])
print(marks+5)
print(marks-5)
print(marks*8)
print(marks/2)

[85 95 65]
[75 85 55]
[640 720 480]


indexing

In [37]:
import numpy as np
marks=np.array([85,90,78,92])
print(marks[3])

92


using arrange()

In [38]:
import numpy as np

a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


using linspace()

In [39]:
import numpy as np

a = np.linspace(1, 10, 5)

print(a)

[ 1.    3.25  5.5   7.75 10.  ]


Reshape an Array

In [40]:
import numpy as np

a = np.arange(1, 13)

b = a.reshape(3, 4)

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
